-- Batch 1: Categories (run this first)
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('banking', 'Banking', 'fa-building-columns', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":25},{"name":"Product Value","max":35},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('mobile-networks', 'Mobile Networks', 'fa-signal', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":20},{"name":"Product Value","max":30},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('hr-software', 'HR Software', 'fa-users-gear', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":25},{"name":"Product Value","max":35},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('accounting-software', 'Accounting Software', 'fa-calculator', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":25},{"name":"Product Value","max":35},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('property-letting', 'Property Letting', 'fa-house-chimney', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":25},{"name":"Product Value","max":35},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('online-retailers', 'Online Retailers', 'fa-cart-shopping', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":20},{"name":"Product Value","max":30},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('medical-aid', 'Medical Aid', 'fa-heart-pulse', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":20},{"name":"Product Value","max":30},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('insurance', 'Insurance', 'fa-shield-halved', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":25},{"name":"Product Value","max":35},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('home-cleaning', 'Home Cleaning', 'fa-spray-can-sparkles', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":20},{"name":"Product Value","max":30},{"name":"Innovation","max":10},{"name":"Customer Support","max":12},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('car-dealers', 'Car Dealers', 'fa-car', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":25},{"name":"Product Value","max":35},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('food-delivery', 'Food Delivery', 'fa-utensils', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":22},{"name":"Product Value","max":32},{"name":"Innovation","max":10},{"name":"Customer Support","max":13},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('armed-response', 'Armed Response', 'fa-shield', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":20},{"name":"Product Value","max":30},{"name":"Innovation","max":10},{"name":"Customer Support","max":12},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
INSERT INTO categories (slug, name, icon, scoring_categories) VALUES ('car-rentals', 'Car Rentals', 'fa-key', $json$[{"name":"Compliance","max":20},{"name":"Customer Satisfaction","max":25},{"name":"Product Value","max":35},{"name":"Innovation","max":10},{"name":"Customer Support","max":15},{"name":"Accessibility & Security","max":10}]$json$::jsonb) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, scoring_categories=EXCLUDED.scoring_categories;
